inherit_from: .rubocop_todo.yml

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 50
  Exclude:
    - 'lib/reudy/irc_client.rb'
    - 'lib/reudy/reudy.rb'

Metrics/BlockLength:
  Max: 28

Metrics/BlockNesting:
  Max: 4

Metrics/CyclomaticComplexity:
  Max: 32

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'lib/reudy/reudy.rb'
    - 'lib/reudy/tango_mgm.rb'
    - 'lib/reudy/word_searcher.rb'

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 28

Performance/Casecmp:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  Enabled: false
